# Generated by Django 5.2 on 2025-04-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_status',
            field=models.CharField(choices=[('confirmed', 'confirm'), ('pending', 'pending')], max_length=20),
        ),
    ]
