# Generated by Django 5.2 on 2025-04-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('thriller', 'thriller'), ('comedy', 'Comedy'), ('drama', 'drama'), ('romance', 'romance'), ('crime', 'crime'), ('action', 'action'), ('animation', 'Animation'), ('biography', 'Biography')], max_length=100)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('French', 'French'), ('kannada', 'kannada'), ('telugu', 'telugu'), ('tamil', 'tamil')], max_length=100)),
                ('synopsis', models.TextField()),
                ('cast', models.TextField()),
                ('duration_minutes', models.IntegerField()),
                ('release_date', models.DateField()),
                ('trailer_url', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
